# Configuration Netlify pour Petit Kangourou

[build]
  # Commande de build
  command = "npm run build"
  # Dossier de sortie
  publish = "dist"

# Configuration des Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Désactiver le scan de secrets (la clé Supabase ANON est publique par design)
[build.environment]
  SECRETS_SCAN_ENABLED = "false"

# Redirection pour React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
